// GENERATED by scripts/gen-paper-index.mjs — do not edit by hand.
import type { FulltextSpec, PaperSpec } from "../paper-spec";
import { paper as p_2021_v26_i1_01 } from "./2021-v26-i1-01";
import { paper as p_2021_v26_i1_02 } from "./2021-v26-i1-02";
import { paper as p_2021_v26_i1_03 } from "./2021-v26-i1-03";
import { paper as p_2021_v26_i1_04 } from "./2021-v26-i1-04";
import { paper as p_2021_v26_i2_01 } from "./2021-v26-i2-01";
import { paper as p_2021_v26_i2_02 } from "./2021-v26-i2-02";
import { paper as p_2021_v26_i2_03 } from "./2021-v26-i2-03";
import { paper as p_2021_v26_i2_04 } from "./2021-v26-i2-04";
import { paper as p_2021_v26_i3_01 } from "./2021-v26-i3-01";
import { paper as p_2021_v26_i3_02 } from "./2021-v26-i3-02";
import { paper as p_2021_v26_i3_03 } from "./2021-v26-i3-03";
import { paper as p_2021_v26_i3_04 } from "./2021-v26-i3-04";
import { paper as p_2022_v27_i1_01 } from "./2022-v27-i1-01";
import { paper as p_2022_v27_i1_02 } from "./2022-v27-i1-02";
import { paper as p_2022_v27_i1_03 } from "./2022-v27-i1-03";
import { paper as p_2022_v27_i1_04 } from "./2022-v27-i1-04";
import { paper as p_2022_v27_i3_01 } from "./2022-v27-i3-01";
import { paper as p_2022_v27_i3_02 } from "./2022-v27-i3-02";
import { paper as p_2022_v27_i3_03 } from "./2022-v27-i3-03";
import { paper as p_2022_v27_i3_04 } from "./2022-v27-i3-04";
import { paper as p_2025_v30_i4_01 } from "./2025-v30-i4-01";
import { paper as p_2025_v30_i4_02 } from "./2025-v30-i4-02";
import { paper as p_2025_v30_i4_03 } from "./2025-v30-i4-03";
import { fulltext as p_2021_v26_i4_01 } from "./2021-v26-i4-01";
import { fulltext as p_2022_v27_i2_01 } from "./2022-v27-i2-01";
import { fulltext as p_2022_v27_i4_01 } from "./2022-v27-i4-01";
import { fulltext as p_2023_v28_i1_01 } from "./2023-v28-i1-01";
import { fulltext as p_2023_v28_i1_03 } from "./2023-v28-i1-03";
import { fulltext as p_2023_v28_i2_01 } from "./2023-v28-i2-01";
import { fulltext as p_2023_v28_i2_03 } from "./2023-v28-i2-03";

export const ALL_PAPERS: PaperSpec[] = [p_2021_v26_i1_01, p_2021_v26_i1_02, p_2021_v26_i1_03, p_2021_v26_i1_04, p_2021_v26_i2_01, p_2021_v26_i2_02, p_2021_v26_i2_03, p_2021_v26_i2_04, p_2021_v26_i3_01, p_2021_v26_i3_02, p_2021_v26_i3_03, p_2021_v26_i3_04, p_2022_v27_i1_01, p_2022_v27_i1_02, p_2022_v27_i1_03, p_2022_v27_i1_04, p_2022_v27_i3_01, p_2022_v27_i3_02, p_2022_v27_i3_03, p_2022_v27_i3_04, p_2025_v30_i4_01, p_2025_v30_i4_02, p_2025_v30_i4_03];

export const ALL_FULLTEXTS: FulltextSpec[] = [p_2021_v26_i4_01, p_2022_v27_i2_01, p_2022_v27_i4_01, p_2023_v28_i1_01, p_2023_v28_i1_03, p_2023_v28_i2_01, p_2023_v28_i2_03];
